name: Publish Docker image to GHCR

on:
  push:
    tags:
      - 'kit-ar/v*.*.*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tag
      id: extract_version
      run: |
        echo "::set-output name=version::${GITHUB_REF#refs/tags/kit-ar/v}"
        echo $version

    - name: Build and push import secret
      uses: docker/build-push-action@v4
      id: docker_build_import_secret
      with:
        file: ./examples/import-secrets/Dockerfile
        context:  ./examples/import-secrets
        platforms: linux/amd64,linux/arm64
        push: true
        tags: "ghcr.io/joaovizoso/vcluster-example-import-secrets:${{steps.extract_version.outputs.version}}"